### ISSUE TITLE
Jeg elsker det

### ISSUE THREAD

**Issue by Gweronx** [nikeedev/rain-lang#1]

**Comment by nikeedev** [comment]
Takk, do you actually talk Norwegian or did you just translate it…?
But thanks, syntax can be copied from other languages, but my point is to make it easy to learn for any other programming language user like for python or cpp

**Comment by Gweronx** [comment]
I'm learning Norwegian on Duolingo for 1 year.

**Comment by nikeedev** [comment]
> I'm learning Norwegian on Duolingo for 1 year.

nice, btw the syntax is now more updated and i begun on the lexer of the compiler

@Gweronx
